server:
  port: 8080

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.xiaows.app.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: root
    password: 123456

# 打印sql
logging:
  level:
    cn.xiaows.app.dao : debug