server:
  port: 8080

mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.xiaows.app.entity

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mydb?useSSL=false
    username: root
    password: 123456
    hikari:
      jdbc-url:
      driver-class-name:
      username:
      password:
  mvc:
    view:
      prefix: /
      suffix: .html

#spring.datasource.hikari.hive.jdbc-url


# 打印sql
logging:
  level:
    cn.xiaows.app.dao: debug
  file: application.log
  pattern:
#    console: %d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}} %clr(%-5p) [%15.15t] %clr(%-50.50logger{49}) : %msg%n
#    console: %clr(%d{${LOG_DATEFORMAT_PATTERN:-yyyy-MM-dd HH:mm:ss.SSS}}){faint} %clr(${LOG_LEVEL_PATTERN:-%5p}) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n${LOG_EXCEPTION_CONVERSION_WORD:-%wEx}
