package cn.xiaows.applogs.dubbo.provider.dao;

import cn.xiaows.applogs.dubbo.provider.entity.User;
import org.apache.ibatis.annotations.Mapper;

import java.util.List;

/**
 *
 * @author: xiaows
 * @create: 2019-01-08 14:59
 * @version: v1.0
 */
@Mapper
public interface UserDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jan 07 17:11:21 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jan 07 17:11:21 CST 2019
     */
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jan 07 17:11:21 CST 2019
     */
    User selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jan 07 17:11:21 CST 2019
     */
    List<User> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbg.generated Mon Jan 07 17:11:21 CST 2019
     */
    int updateByPrimaryKey(User record);
}