package cn.xiaows.app.dao;

import cn.xiaows.app.entity.Project;
import java.util.List;

/**
 *
 * @author: xiaows
 * @create: 2019-01-08 14:56
 * @version: v1.0
 */
public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sat Jan 05 19:19:00 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sat Jan 05 19:19:00 CST 2019
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sat Jan 05 19:19:00 CST 2019
     */
    Project selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sat Jan 05 19:19:00 CST 2019
     */
    List<Project> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project
     *
     * @mbg.generated Sat Jan 05 19:19:00 CST 2019
     */
    int updateByPrimaryKey(Project record);
}